### ISSUE TITLE
[Feature request] list recent day's entries

### ISSUE THREAD

**Issue by TobiVanHelsinki** [danielroehrig/diary#22]
Hi I am dropping the idea:
The Nav Panel Space could be used to show a quick preview of the last entries.
Maybe code could get re-used from the widget Feature Request #20🤔

See the bottom part of my amazing sketch for inspiration.

![FR](https://user-images.githubusercontent.com/6724862/160238916-009f3ed9-c259-43f1-89f9-ded1c5a3f06b.png)

Again, thank you for improving nextcloud ecosystem :)

**Comment by danielroehrig** [comment]
I like the nav panel idea with the last three entries and the first sentence. I will try to implement this. The calendar might get thrown out and replaced with something that can be localized on the fly.

**Comment by punkyard** [comment]
hi, a list of all entries could be appropriate ..
why writing if we can't read easily afterwards?

**Comment by danielroehrig** [comment]
Do you mean **ALL** entries in a list? That will soon be a very long list. I would like to see the last 3-5 entries there and if you want to read the entries, you can use the calendar. 

I am currently working on a very basic mobile app for the diary so please excuse the lack of progress here for a while.

**Comment by punkyard** [comment]
i'd say at least a list of entries per month
so far I won't use it the way it is
you understand we not going to probe every date to check if there was anything in it, right?
(i say we cause we could use it as a diary for the team 👍)

**Comment by danielroehrig** [comment]
My ideas for the future are

- having a "go to previous / next entry" button
- marking days with entries in the calendar (blue background or something
- displaying the last 3-5 entries

Would that be okay?

**Comment by punkyard** [comment]
Hi 
theses seems very useful features for your app!
+ could you show a field in which user can decide how many of last entries one'd like to display

+++ listing all entries under each mouth would be amazing
i think that's also @TobiVanHelsinki's suggestion

**Comment by danielroehrig** [comment]
Thanks for all your input. As soon as I get back into it, I will start implementing whatever is the easiest first and then start working from there. :wink:

**Comment by punkyard** [comment]
bon courage !
and keep me posted ;)

**Comment by TobiVanHelsinki** [comment]
> +++ listing all entries under each mouth would be amazing i think that's also @TobiVanHelsinki's suggestion

No! A list of all entries was not my mind - but I wasn't very clear, thow.

I agree, the biggest addition would be a coloring of the mini-month view.
I think the list is more of an eye candy and to keep it performant I would see 3-5 of the entries prior to the current date and 1-2 entries after the selected entrie (if you edit something in the past).

Anyhow I had the idead of combining this short list with a lazy loading mechanism to infinetly scroll through all entries ... but well, this would be an overkill at this time ;)

Best regards
TvH

**Comment by rollanders** [comment]
I would propose to list all entries during a specified time, in my case last month's entries.

**Comment by TobiVanHelsinki** [comment]
I just updated the App and the list looks pretty neat. 👍

**Comment by danielroehrig** [comment]
Cool! I am not 100% sure about the UI and UX but it's a start.
