### ISSUE TITLE
Some elements don't have proper margins (i.e. lists and quotes)

### ISSUE THREAD

**Issue by tecc** [danielroehrig/diary#29]
Lists and quotes don't have proper margins, which causes them to go outside of the visible area.

For example, given the following entry:
```markdown
This should have a margin on the left:
1. But it doesn't
2. So it has to be fixed

> This should too, alongside an indication that it's a quote (e.g. a bar on the left, although this is up to the implementer).

* Oh, and it also applies to these too.
* Because why wouldn't it? This is also a list.
```

If I were to put that here in GitHub, it would look fine:

This should have a margin on the left:
1. But it doesn't
2. So it has to be fixed

> This should too, alongside an indication that it's a quote (e.g. a bar on the left, although this is up to the implementer).

* Oh, and it also applies to these too.
* Because why wouldn't it? This is also a list.

But in the app, it looks like this:

![image](https://user-images.githubusercontent.com/38840234/165910677-e73853ce-cbda-4764-b7b2-4ba8b74aecc1.png)

Yeah... this should probably be fixed.

**Comment by danielroehrig** [comment]
This is not my code and I can't change that. But I agree, that the preview functionality has some issues. If you want to, you can raise this issues with the maintainer of this repository: https://www.npmjs.com/package/vue-simplemde

**Comment by tecc** [comment]
Well, it isn't your code, true, but it's entirely fixable. I mostly left this issue here as a very clear to-do item.
I mean, see #24 - all that's required is a little understanding of the element structure and it's quite easy to fix.
I'm going to fix it in my fork and make a PR for it when I'm done.

**Comment by danielroehrig** [comment]
That problem was, that I forgot to include a stylesheet that determines the preview css. Actually, you have to choose between three stylesheets. I will do that with the next release. Thanks for pointing that out that the preview was off! I never use that function.

**Comment by tecc** [comment]
Ah, okay.
Looking forward to the next release then!
