### ISSUE TITLE
Please add nextcloud-bot with admin permissions so it can push translations

### ISSUE THREAD

**Issue by nickvergessen** [danielroehrig/diary#34]
Seems you tried to set up transifex sync and we also added the cron job on our side.
But since main is "protected" the bot (https://github.com/nextcloud-bot) needs to be added as admin so it can push to the branch never the less.
Currently it spams our log with an error.

If you don't want to do this, we can also remove the syncing mechanism again.

**Comment by danielroehrig** [comment]
I was following [these instructions](https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html?highlight=translation)

> Now the GitHub account [@nextcloud-bot](https://github.com/nextcloud-bot) needs to get write access to your repository. It will run every night and only push commits to the master branch once there is an update to the translation. In general you should enable the [protected branches feature](https://help.github.com/articles/configuring-protected-branches/) at least for the master branch.

How can I give nextcloud-bot admin permissions? I would have guessed that it's in the settings -> collaborators -> manage access but all I can do is remove the access
![image](https://user-images.githubusercontent.com/12596513/169150906-a6da6734-7a40-4944-8847-ef45dfdd80fa.png)

So, I would like to give nextcloud-bot admin access, I just don't  know how.

**Comment by danielroehrig** [comment]
Alternatively, I just remove the branch protection and hope, no collaborator does a force push to master...

**Comment by nickvergessen** [comment]
Ah, I guess it does not work because it's a personal repo and not an Organisation owned one.
So yeah, either you remove branch protection, move it to an organization owned by you or we move it to the Nextcloud org? 🙃

**Comment by danielroehrig** [comment]
I mean, I don't own an organization but I'm fine with removing the protection for now and also moving it to nextcloud org. It's still very rough around ALL edges though. So maybe let it mature a bit before doing that?

I removed the protection. Does it work now?

**Comment by nickvergessen** [comment]
We will see tonight around 3/4am UTC, that's when the sync runs.

**Comment by danielroehrig** [comment]
:popcorn:

**Comment by nickvergessen** [comment]
https://github.com/danielroehrig/diary/commit/03c829f681e2366fcc006dfa17c2f95995f9631e

Seems to have worked

**Comment by nickvergessen** [comment]
Did you accidentally readd this or is develop protected but you now made it the default branch?

```
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: Changes must be made through a pull request.
To github.com:danielroehrig/diary
 ! [remote rejected] develop -> develop (protected branch hook declined)
```

**Comment by danielroehrig** [comment]
I removed the branch protection from main, because that's what was needed. I can also remove the protection from develop. Should I?

**Comment by danielroehrig** [comment]
Okay. I did it. Try again.
