### ISSUE TITLE
Date and navigation button

### ISSUE THREAD

**Issue by Valdnet** [danielroehrig/diary#36]
I have noticed the following issues:

1. When the application was first launched, the date in the diary header was not translated. The translated date and in the appropriate form of the set time zone was changed only after adding the entry.
2. The date form displayed on the calendar button does not match the set time zone.
3. The calendar does not have translated months (the problem may be related to the above error).
4. The close and open navigation button is too close to the date and navigation sideline (no margin).
5. When opening the diary, its record appears (an asterisk appears next to the diary's header). In my opinion, saving should appear only after changing the content.
6. When you hover over the text "Export" of the diary, the cursor changes to a hand, which incorrectly informs the user about the export function.

Refers to point 1, 2, 4 and 5:

![obraz](https://user-images.githubusercontent.com/47037905/169232516-7811d99a-f00a-4b31-abfc-575bb22446ad.png)
Refers to point 3:

![obraz](https://user-images.githubusercontent.com/47037905/169234824-6c2855a6-173e-4945-9cd4-46689dde517e.png)
Refers to point 6:

![obraz](https://user-images.githubusercontent.com/47037905/169236046-526b3a6f-dd7e-4222-9f65-3c4112fa58c8.png)

Apps:
Nextcloud 24.0.0
Diary 0.0.5

**Comment by danielroehrig** [comment]
1-3 :The calendar that is currently used is hard to translate. I will likely switch to a different one. 
4.: I will look into it
5. I am fighting a bit with the automatic save function and vue router.
6. That's a nextcloud-vue component but I will look into it.
