### ISSUE TITLE
the update 0.0.6. is not available in the update stream

### ISSUE THREAD

**Issue by EmJotGeh** [danielroehrig/diary#37]

**Comment by danielroehrig** [comment]
According to the apps store it should be: https://apps.nextcloud.com/apps/diary

For me, it sometimes takes a couple of hours to be recognized by my nextcloud server, so please tell me if the problem persists tomorrow.

**Comment by EmJotGeh** [comment]
thanks, I'll do it.

**Comment by danielroehrig** [comment]
![image](https://user-images.githubusercontent.com/12596513/169713621-02e9967f-e879-4454-85db-a8a1d8e9e691.png)
I just updated my server. Try again.

**Comment by EmJotGeh** [comment]
the update is not available yet, but I'll try it again in a few minutes. Thanks

**Comment by EmJotGeh** [comment]
The update hasn't arrived yet. Other apps could be updated as usual.

**Comment by danielroehrig** [comment]
Is that still a problem?

**Comment by EmJotGeh** [comment]
Yes, unfortunately. There is no update and Diary can no longer be activated after the last Nextcloud 24.0.1 update
![Screenshot_20220530_170022](https://user-images.githubusercontent.com/16000642/171019090-a7d0b610-564a-44d7-9b78-bb33f1db8dd6.jpeg)
.

**Comment by danielroehrig** [comment]
So the problem is that it's not available for nextcloud 24? I test on 23, so that might be the problem, right?

**Comment by danielroehrig** [comment]
Nextcloud 24 should work, but only PHP Version 8.0 is supported. Could you check, if you have version 8.1 running?

**Comment by bnthn** [comment]
Im on Nextcloud 24 with php version 8.1.5 and for me the app also did not appear as download in nextcloud itself, i had to download it from the releases on github and got the php max-version error until i changed it as in #42

**Comment by EmJotGeh** [comment]
I'm a little bit confused, it wasn't because of Pentecost :-D but Diary is now running with NC 24 on PHP 8.1. Is that right? In my case it seems to be working fine. Thank's

**Comment by danielroehrig** [comment]
We checked and Version 8.1 seemed to work so we lifted the resctrictions.
