### ISSUE TITLE
PHP with a version lower than 8.0 is required.

### ISSUE THREAD

**Issue by bnthn** [danielroehrig/diary#42]
I don't know if this is on purpose. I'm using PHP version 8.1.5

**Comment by danielroehrig** [comment]
The current php max version is 8.0 but I will look into this.

**Comment by danielroehrig** [comment]
I cannot find a way to update my docker dev environment to php 8.1. I suppose it should work with Version 8.1 and all that needs to be done is to set the max-php-version number to 8.1 But if I can't test it, I'm reluctant to do it. Could you try it?

**Comment by danielroehrig** [comment]
#37

**Comment by bnthn** [comment]
I did as you say and changed the php max-version in appinfo/info.xml as you suggested. I can write entries, export them as pdf and markdown, and all the styling seems to work too. Also, everything still seems fine after reboot.

**Comment by danielroehrig** [comment]
![image](https://user-images.githubusercontent.com/12596513/172070219-d2834cf6-c202-45a0-9523-87076875b9af.png)
I mean, I did write some tests... lets see if they work

**Comment by danielroehrig** [comment]
This seems to work. I will add support for PHP 8.1 in the next release
