### ISSUE TITLE
[Feature request] Save button / save indicator

### ISSUE THREAD

**Issue by pil-in-a** [danielroehrig/diary#44]
It happened to me few times, that I lost last paragraph or last edit, when I left the page (to other app in NC, closed the tab).
So I am suggesting adding some save button or save indicator to assure me, that nothing will be lost.
It could be placed in the format buttons row, maybe?

**Comment by danielroehrig** [comment]
Oh. That shouldn't happen. Saving is done like one second after the last keystroke and there is an indicator next to the date. As long as you see an asterisk next to the date, you have unsaved changes. Wait a second and the asterisk should disappear. Moving the mouse to a save button an clicking should be slower. Could you tell me, if you see the indicator and if auto-saving works as intented?

I'd rather have something like a detection of some sort that prevents closing the window as long as there are uncommited changes.

**Comment by pil-in-a** [comment]
Oh, I'm sorry I missed that :-)
I can see asterisk and It really disappears after a second or so.
It is also hard to replicate the issue - It appears to be quite random. But it happened few times (maybe more on mobile browser but not exclusively) and as I see it now I don't think I closed the tab so quickly in those situations.
So I could try to find errors on my side (running NC:latest in Docker).

**Comment by danielroehrig** [comment]
It's good to know these issues exist and I will try to find ways to mitigate them. Maybe using local storage before sending it to the backend.

**Comment by pil-in-a** [comment]
Hello. I've found something interesting about problem we discussed. When I quickly browse through days via arrows next to the date (quicker than asterisk disappears), sometimes entire entry is copied to another day, overwriting existing entry. Resulting in having duplicate entry tow days in the row.

**Comment by danielroehrig** [comment]
Okay. That sounds ... bad. I will investigate. Thanks!

**Comment by danielroehrig** [comment]
I was unable to replicate that issue locally. Steps that I took:

1. Create a new entry somewhere in the middle of the month
2. Frantically use the arrow buttons to move over this date
3. Nothing happens

Could you try to tell me the exact circumstances in which these errors occur? Because I really don't want anyone to lose their entries.

**Comment by danielroehrig** [comment]
I think I found the problem and I may have a solution. Is it pretty? No. Will it work? Probably. Would I really love someone with more in-depth experience with simlemde or vuesimplemde to take a look? Absolutely! But for the time being, this will have to do. Will be released with the next version.

**Comment by danielroehrig** [comment]
The latest version 0.0.8 is out and this should be fixed now.

**Comment by pil-in-a** [comment]
Hello. I am using it again for a few weeks now and everything seems to be working fine. Thanks.
