### ISSUE TITLE
Diary - is not available for installation

### ISSUE THREAD

**Issue by EmJotGeh** [danielroehrig/diary#5]
Hi, i want to to test your Diary app but it's not available for installation.

**Comment by danielroehrig** [comment]
@EmJotGeh, I published it as a nightly as I wanted to make that I only wreck my own server before I wreck somebody elses. So, as of now, you would have to install it by extracting the tar.gz into the apps folder. I know of some bugs and some glitches. Should I go on and just release it as is and everybody who installs a 0.0.1 version should know what they're doing? Or should I wait?

**Comment by EmJotGeh** [comment]
Hallo Daniel,

ich mach es mal eben auf Deutsch. Ich würde auf apps.nextcloud.com die App als Alpha oder Beta kennzeichnen und eben noch erwähnen das die noch nicht für den Produktiven Einsatz ausgelegt ist. Ich denke, dass es für Nextcloud Nutzer so einfacher ist, wenn sie die App direkt aus dem Apps Repository  installieren können um die App zu testen und Dir damit auch ein entsprechendes Feedback zu geben.

**Comment by EmJotGeh** [comment]
Ich denke, wichtig ist vor allem dieses einmal im Beschreibungstext der App als Alpha oder Beta zu kennzeichnen. Damit sollten dann alle wissen, die Deine App testen wollen, dass die App möglicherweise Fehler enthält. Nur sollte die App eben über den Nextcloud Installer installierbar sein. Ich denke, damit erreicht man einfach mehr Leute die die App schnell mal testen wollen oder die sichtbare Entwicklung leichter nachvollziehen können wenn sie die App installiert haben und dann auch fortlaufen aktualisiert wird.

**Comment by danielroehrig** [comment]
Habe die App veröffentlich und die Beschreibung angepasst, und ich sehe es im Appstore, aber ich kann es nicht installieren bzw. es wird nicht gefunden, wenn ich auf apps gehe und nach "diary" suche. Vielleicht hast du mehr Glück. Das nightly flag habe ich eigentlich rausgenommen.

**Comment by Weiming-Hu** [comment]
Hi Daniel! Thank you so much for your contribution to the app. I will definitely be interested in testing it out for you. I will watch out for updates in the future.

**Comment by EmJotGeh** [comment]
Hallo Daniel,

ich hab Deine App heute ohne Probleme installieren können. Ich denke es gibt nur ein paar Verzögerungen beim veröffentlichen auf apps.nextcloud.com.

**Comment by danielroehrig** [comment]
@Weiming-Hu it's now available on the app store.
