### ISSUE TITLE
Nextcloud 25 support

### ISSUE THREAD

**Issue by bin101** [danielroehrig/diary#54]
Since Nextcloud 25.0.1 is now available in the stable channel, it would be nice if the version would also be supported.

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by bin101** [comment]
@danielroehrig Do you have any plans to still support this plugin?

**Comment by danielroehrig** [comment]
Absolutely, but currently I have to get a kid into a school and I am also switching jobs and programming languages, I am a bit short on time.

**Comment by danielroehrig** [comment]
Update: I set up my dev environment to nextcloud 25 and it seems to be working. The stylesheets seem to be a bit off, but I will release it as soon as I can.

**Comment by bin101** [comment]
@danielroehrig so do you want to fix this CSS issues first?

**Comment by danielroehrig** [comment]
TBH, I would really like some help here. It looks bad. I don't know how to make it look less bad. I have weird spacing, can't get the icons to work and somehow even the color is off. I don't want to ship it like this but I have little time (and patience or passion) to fix CSS. Could anybody help me out?

**Comment by kylecoberly** [comment]
Hey @danielroehrig, I can probably help. Can you point me to some resources on how I can get this running in a test environment?

**Comment by danielroehrig** [comment]
That would be awesome! I wrote a blog entry about how I set up a dev environment: https://www.a-broad-view.com/tech-talk/setting-up-a-development-environment-to-work-on-a-new-nextcloud-app-with-docker/
Your mileage might vary but it's a start. Hit me up if I can help you.

**Comment by kylecoberly** [comment]
Cool, digging in on this today!

**Comment by danielroehrig** [comment]
There is a branch called update-css. It's where I updated the libraries. It's a good place to start.

**Comment by kylecoberly** [comment]
![image](https://user-images.githubusercontent.com/1958931/213609781-f30f5955-3900-46b3-baf2-209d12655880.png)
Got it working locally! I think I can totally fix this, standby.

**Comment by kylecoberly** [comment]
![image](https://user-images.githubusercontent.com/1958931/213637943-9e16432a-b177-45c5-a8ce-62a06b1aec8f.png)
![image](https://user-images.githubusercontent.com/1958931/213638140-cc1bf19a-5884-4b49-a61e-d6816152f8e5.png)

I think I got it! PRing.

**Comment by danielroehrig** [comment]
Thank you! I will merge it and release it.

**Comment by kylecoberly** [comment]
Just upgraded, working great!
