### ISSUE TITLE
How can i delete an entry? Where are the entry saved?

### ISSUE THREAD

**Issue by stefan-franz** [danielroehrig/diary#65]
Nice App - i like it. But how to delete and i don't find where the entries are saved

**Comment by stefan-franz** [comment]
AH - ok. 
Maybe you make in the future a possibility, to delete entry from - to (e.g. to delete entrys of a month or year....)
Nice App - i like it.

**Comment by danielroehrig** [comment]
Thank you! I think, someone already suggested that. Or maybe it was you. I don't really understand, why you would delete diary entries. Even more, multiple ones. Why would you want to do that? For me, that beats the purpose of a diary.

**Comment by stefan-franz** [comment]
For me is your diary a helping tool to expand with my personality and my business. writing Ideas and so on. 
Older things (older than one year) can be delete from time to time (in my case). Such a deleting feature would offer it.

**Comment by danielroehrig** [comment]
If you want to use Nextcloud for that, maybe the notes app is better suited for you. You could also use [Obsidian](https://obsidian.md). I only heard good things about it.

**Comment by stefan-franz** [comment]
I have all my data on the nextcloud so for this your diary is perfect. Deleting feature would nice, but isn't essential for life
