### ISSUE TITLE
Writing an entry and immediately going to the previous date won't update the text

### ISSUE THREAD

**Issue by danielroehrig** [danielroehrig/diary#7]
1. Write entry
2. Go to previous date
3. Entry doesn't change

After some time it works but I don't know why.

**Comment by Weiming-Hu** [comment]
Same issue here.

**Comment by danielroehrig** [comment]
I know. It's still very rough around the edges. Will fix that as soon as possible.

**Comment by danielroehrig** [comment]
Fixed. Will be in the next release.

**Comment by Weiming-Hu** [comment]
I'm just being curious. Can you show me maybe the code change or the PR that fixes this issue? Thanks.

**Comment by danielroehrig** [comment]
Sure. [src/Editor.vue](https://github.com/danielroehrig/diary/pull/14/files#diff-ab7755f2ea23cb784bffab595b1ca31f05f215e767afe538b45596511a30397c) Line 104-106

**Comment by Weiming-Hu** [comment]
Thanks.
